export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const GET_ALL_TRANSACTION_SUCCESS = 'GET_ALL_TRANSACTION_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const AUTH_ERROR = 'AUTH_ERROR';